name: "Mosher's Automotive"
favicon: null
layout_spectrum: 0.7255319
typography_spectrum: 0.9845102
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#171717'
    - '#8a8a8a'
    - '#ffb810'
    - '#b50706'
  brandStrength: 0.4409064
  lightness: 0.3361702
  saturation: 0.4723404
  rhythmicContrast: 0.6361702
purpose: []
